### ISSUE TITLE
[Feature request]: Update frontend_url with correct app name

### ISSUE THREAD

**Issue by magnuswiden** [triggerfishab/lisa-cli#14]
### Feature request

In _trellis/group_vars/production/wordpress_sites.yml_ and _trellis/group_vars/staging/wordpress_sites.yml_ it would be nice if the env variabel `frontend_url` is updated with the app name. I.e. `https://[NAME-OF-PROJECT]-app.vercel.app/`

**Comment by moelleer** [comment]
Fixed in https://github.com/triggerfishab/lisa-cli/releases/tag/v2.10.0
