### ISSUE TITLE
[Bug]: Crash b/c 1Password is locked

### ISSUE THREAD

**Issue by lissmeister** [triggerfishab/lisa-cli#53]
### What happened?

Lisa crashed because 1Password was locked 

### Lisa CLI status

 A summary of your Lisa setup

 ️💁 Your path is: /Users/liss/dev/sites
 ️💁 Versions of your packages:
   Lisa CLI: 2.12.0
   1Password CLI: 2.21.0
   Ansible: 2.15.4
   AWS CLI: 2.13.21
   GitHub CLI: 2.35.0
   Node: 20.7.0
   Trellis CLI: 1.11.1
   Valet: 3.3.2
   Vercel: 29.3.0
   WP CLI: 2.8.1
   Composer: 2.6.3
   PHP: 8.1.23

### Relevant log output

```shell
❯ lisa kinsta create

⚡️ Creating Kinsta site!

node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: op item get l2i57yslyjfr5jsieew4imwxgq --fields label="kinsta.api key",label="kinsta.company id"
[ERROR] 2023/09/29 09:31:22 error initializing client: 1Password app is locked. Please open 1Password, unlock it with your password, and then try again

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'op item get l2i57yslyjfr5jsieew4imwxgq --fields label="kinsta.api key",label="kinsta.company id"',
  stdout: '',
  stderr: '[ERROR] 2023/09/29 09:31:22 error initializing client: 1Password app is locked. Please open 1Password, unlock it with your password, and then try again\n'
}

Node.js v20.7.0
```

**Comment by chrillep** [comment]
@lissmeister röcker det med try catch och endast skicaka vidare
"error initializing client: 1Password app is locked. Please open 1Password, unlock it with your password, and then try again" ?

**Comment by lissmeister** [comment]
@chrillep https://github.com/triggerfishab/lisa-cli/pull/52/commits/435f58298955c3f8030a89effc0e4766ce99455f
