### ISSUE TITLE
No site path found error message prevents setting path

### ISSUE THREAD

**Issue by mtws** [triggerfishab/lisa-cli#8]
After installing the package and running `lisa` the error message `🚨 No site path was found, please run lisa path to set one!` is shown. Even when trying to run `lisa path ~/Sites`.

Fixed this locally by temporarily commenting out `process.chdir(getSitesPath())` in `initProgram`. After that I was able to run `lisa path ~/Sites` and then uncomment `process.chdir(getSitesPath())`.

**Comment by moelleer** [comment]
@mtws Fixed in https://github.com/triggerfishab/lisa-cli/releases/tag/v2.7.0
